initial workflow rework
0xPolygon/go-ibft pull request #33
Opened 2022-10-20 22:33 UTC by epikichi

# Description

Introducing Github workflow rework to improve experience.
- Reusable workflows
- Snyk integration

2022-11-01 06:19 UTC, b00ris requested changes
Overall - looks good!

2022-11-01 06:19 UTC, b00ris commented on .golangci.yml
> +run:
Could i ask you to change lint command(in makefile) to use this config?

2022-11-02 14:53 UTC, zivkovicmilos approved these changes
Looks great 💯

2022-11-02 14:55 UTC, merged

2022-11-02 15:13 UTC, vcastellm reviewed
Late LGTM